name: Crawler

on:
  schedule:
    - cron: '03,27,51 22 * * *'
    - cron: '11 0,23 * * *'
    - cron: '17 2-14/4 * * *'
  repository_dispatch:
    types:
      - start_crawl

env:
  TZ: Asia/Tokyo

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Checkout Data
        uses: actions/checkout@v4
        with:
          ref: main
          path: data
      - name: Run Crawler
        run: |
          docker compose run --rm crawler
        env:
          COMPOSE_FILE: compose.crawler.yaml
          WORKDIR: /var/app/eiketsu-taisen-data
          CRAWLER_IMAGE: ghcr.io/${{ github.repository }}:crawler
          PUPPETEER_NAVIGATION_TIMEOUT: 120000
          TARGET_URL: https://eiketsu-taisen.net/datalist/
          GIT_USER_NAME: 'eiketsu-taisen-data BOT'
          GIT_USER_EMAIL: 'eiketsu-taisen-data@example.com'
          CLIENT_USER_AGENT: ${{ secrets.CLIENT_USER_AGENT }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_INFO_CHANNEL_ID: ${{ secrets.SLACK_INFO_CHANNEL_ID }}
          SLACK_ERROR_CHANNEL_ID: ${{ secrets.SLACK_ERROR_CHANNEL_ID }}
      - name: Push Data
        working-directory: data
        run: |
          git push
      - name: Run Converter
        run: |
          docker compose run --rm crawler npm run converter
        env:
          COMPOSE_FILE: compose.crawler.yaml
          WORKDIR: /var/app/eiketsu-taisen-data
          CRAWLER_IMAGE: ghcr.io/${{ github.repository }}:crawler
          GIT_USER_NAME: 'eiketsu-taisen-data BOT'
          GIT_USER_EMAIL: 'eiketsu-taisen-data@example.com'
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_INFO_CHANNEL_ID: ${{ secrets.SLACK_INFO_CHANNEL_ID }}
          SLACK_ERROR_CHANNEL_ID: ${{ secrets.SLACK_ERROR_CHANNEL_ID }}
      - name: Push Converted Data
        working-directory: data
        run: |
          git push
  trigger_ci:
    needs: crawler
    runs-on: ubuntu-latest
    steps:
      # Github Actionsのデプロイを待つためSleep
      - name: Waiting
        run: |
          sleep 90
      - name: Trigger CI for eiketsu-taisen-net-datalist
        run: |
          curl -H "Authorization: token $TOKEN" -H 'Content-Type: application/json' -X POST https://api.github.com/repos/$REPO/dispatches -d "{\"event_type\":\"$EVENT_TYPE\",\"client_payload\":{}}"
        env:
          TOKEN: ${{ secrets.TRIGGER_CI_TOKEN }}
          REPO: boushi-bird/eiketsu-taisen-net-datalist
          EVENT_TYPE: trigger_ci
